name: OEM GSI Maker

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'Firmware download link'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debloat the OS
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
        sudo docker image prune --all --force
        sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y e2fsprogs android-sdk-libsparse-utils python3-pip brotli gh
        pip3 install -r requirements.txt
        pip3 install pycryptodome

    - name: Download firmware
      run: |
        mkdir -p roms
        wget -O "roms/rom.zip" "${{ inputs.rom_url }}"

    - name: Run GSIMaker
      run: |
        python3 cgsi.py

    - name: Package output
      run: |
        cd IMG/out
        zip -r gsi_output.zip .

    - name: Split ZIP if needed
      run: |
        cd IMG/out
        split -b 1900M gsi_output.zip gsi_output.zip.part_

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        TAG_NAME="gsi-$(date +%Y%m%d-%H%M)"
        gh release create "$TAG_NAME" --title "GSI Build $TAG_NAME" --notes "Auto-generated GSI from ${{ inputs.rom_url }}"

    - name: Upload to GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        TAG_NAME=$(gh release list --limit 1 | awk '{print $1}')
        gh release upload "$TAG_NAME" IMG/out/gsi_output.zip.part_*
